// Generated by view binder compiler. Do not edit!
package com.example.fududelivery.Customer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.LinearLayoutCompat;
import androidx.appcompat.widget.SwitchCompat;
import androidx.appcompat.widget.Toolbar;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.fududelivery.R;
import com.google.android.material.textfield.TextInputEditText;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUpdateAddAddressBinding implements ViewBinding {
  @NonNull
  private final LinearLayoutCompat rootView;

  @NonNull
  public final TextInputEditText detailAddress;

  @NonNull
  public final TextInputEditText fullName;

  @NonNull
  public final TextInputEditText phoneNumber;

  @NonNull
  public final SwitchCompat setDefault;

  @NonNull
  public final Toolbar toolbar;
  @NonNull
  public final TextView txtDetailAddress;

  @NonNull
  public final Button save_button;

  private ActivityUpdateAddAddressBinding(@NonNull LinearLayoutCompat rootView,
                                          @NonNull TextInputEditText detailAddress,
                                          @NonNull TextInputEditText fullName, @NonNull TextInputEditText phoneNumber,
                                          @NonNull SwitchCompat setDefault, @NonNull Toolbar toolbar,
                                          @NonNull TextView txtDetailAddress, @NonNull Button save_button)  {
    this.rootView = rootView;
    this.detailAddress = detailAddress;
    this.fullName = fullName;
    this.phoneNumber = phoneNumber;
    this.setDefault = setDefault;
    this.toolbar = toolbar;
    this.txtDetailAddress = txtDetailAddress;
    this.save_button = save_button;
  }

  @Override
  @NonNull
  public LinearLayoutCompat getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUpdateAddAddressBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUpdateAddAddressBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_customer_addnewaddress, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUpdateAddAddressBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {

      id = R.id.detail_address;
      TextInputEditText detailAddress = ViewBindings.findChildViewById(rootView, id);
      if (detailAddress == null) {
        break missingId;
      }

      id = R.id.full_name;;
      TextInputEditText fullName = ViewBindings.findChildViewById(rootView, id);
      if (fullName == null) {
        break missingId;
      }

      id = R.id.phone_number;
      TextInputEditText phoneNumber = ViewBindings.findChildViewById(rootView, id);
      if (phoneNumber == null) {
        break missingId;
      }

      id = R.id.set_default;
      SwitchCompat setDefault = ViewBindings.findChildViewById(rootView, id);
      if (setDefault == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.txt_detail_address;
      TextView txtDetailAddress = ViewBindings.findChildViewById(rootView, id);
      if (txtDetailAddress == null) {
        break missingId;
      }

      id = R.id.save_button;
      Button save_button = ViewBindings.findChildViewById(rootView, id);
      if (save_button == null) {
        break missingId;
      }

      return new ActivityUpdateAddAddressBinding((LinearLayoutCompat) rootView,
              detailAddress, fullName, phoneNumber, setDefault, toolbar, txtDetailAddress,
              save_button);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
