// Generated by view binder compiler. Do not edit!
package com.example.fududelivery.Customer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RadioButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.fududelivery.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemAddressBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final RadioButton choose;

  @NonNull
  public final TextView defaultText;

  @NonNull
  public final TextView detailAddress;

  @NonNull
  public final TextView receiverName;

  @NonNull
  public final TextView receiverPhoneNumber;

  @NonNull
  public final ImageView update;

  private ItemAddressBinding(@NonNull CardView rootView, @NonNull RadioButton choose,
      @NonNull TextView defaultText, @NonNull TextView detailAddress,
      @NonNull TextView receiverName, @NonNull TextView receiverPhoneNumber,
      @NonNull ImageView update) {
    this.rootView = rootView;
    this.choose = choose;
    this.defaultText = defaultText;
    this.detailAddress = detailAddress;
    this.receiverName = receiverName;
    this.receiverPhoneNumber = receiverPhoneNumber;
    this.update = update;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemAddressBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemAddressBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_address, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemAddressBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.choose;
      RadioButton choose = ViewBindings.findChildViewById(rootView, id);
      if (choose == null) {
        break missingId;
      }

      id = R.id.default_text;
      TextView defaultText = ViewBindings.findChildViewById(rootView, id);
      if (defaultText == null) {
        break missingId;
      }

      id = R.id.detail_address;
      TextView detailAddress = ViewBindings.findChildViewById(rootView, id);
      if (detailAddress == null) {
        break missingId;
      }

      id = R.id.receiver_name;
      TextView receiverName = ViewBindings.findChildViewById(rootView, id);
      if (receiverName == null) {
        break missingId;
      }

      id = R.id.receiver_phone_number;
      TextView receiverPhoneNumber = ViewBindings.findChildViewById(rootView, id);
      if (receiverPhoneNumber == null) {
        break missingId;
      }

      id = R.id.update;
      ImageView update = ViewBindings.findChildViewById(rootView, id);
      if (update == null) {
        break missingId;
      }

      return new ItemAddressBinding((CardView) rootView, choose, defaultText, detailAddress,
          receiverName, receiverPhoneNumber, update);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
