// Generated by view binder compiler. Do not edit!
package com.example.fududelivery.Customer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.fududelivery.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LayoutFailToastBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final LinearLayout backgroundFailToast;

  @NonNull
  public final CardView layoutFailToast;

  @NonNull
  public final TextView txtContentMessage;

  private LayoutFailToastBinding(@NonNull CardView rootView,
      @NonNull LinearLayout backgroundFailToast, @NonNull CardView layoutFailToast,
      @NonNull TextView txtContentMessage) {
    this.rootView = rootView;
    this.backgroundFailToast = backgroundFailToast;
    this.layoutFailToast = layoutFailToast;
    this.txtContentMessage = txtContentMessage;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static LayoutFailToastBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LayoutFailToastBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.layout_fail_toast, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LayoutFailToastBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backgroundFailToast;
      LinearLayout backgroundFailToast = ViewBindings.findChildViewById(rootView, id);
      if (backgroundFailToast == null) {
        break missingId;
      }

      CardView layoutFailToast = (CardView) rootView;

      id = R.id.txtContentMessage;
      TextView txtContentMessage = ViewBindings.findChildViewById(rootView, id);
      if (txtContentMessage == null) {
        break missingId;
      }

      return new LayoutFailToastBinding((CardView) rootView, backgroundFailToast, layoutFailToast,
          txtContentMessage);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
