// Generated by view binder compiler. Do not edit!
package com.example.fududelivery.Customer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Guideline;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.fududelivery.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LayoutAlertDialogBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnNo;

  @NonNull
  public final Button btnYes;

  @NonNull
  public final ConstraintLayout constraintLayout6;

  @NonNull
  public final Guideline guideline5;

  @NonNull
  public final ConstraintLayout layoutAlertDialog;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final TextView txtContentMessage;

  private LayoutAlertDialogBinding(@NonNull ConstraintLayout rootView, @NonNull Button btnNo,
      @NonNull Button btnYes, @NonNull ConstraintLayout constraintLayout6,
      @NonNull Guideline guideline5, @NonNull ConstraintLayout layoutAlertDialog,
      @NonNull LinearLayout linearLayout, @NonNull TextView txtContentMessage) {
    this.rootView = rootView;
    this.btnNo = btnNo;
    this.btnYes = btnYes;
    this.constraintLayout6 = constraintLayout6;
    this.guideline5 = guideline5;
    this.layoutAlertDialog = layoutAlertDialog;
    this.linearLayout = linearLayout;
    this.txtContentMessage = txtContentMessage;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LayoutAlertDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LayoutAlertDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.layout_alert_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LayoutAlertDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnNo;
      Button btnNo = ViewBindings.findChildViewById(rootView, id);
      if (btnNo == null) {
        break missingId;
      }

      id = R.id.btnYes;
      Button btnYes = ViewBindings.findChildViewById(rootView, id);
      if (btnYes == null) {
        break missingId;
      }

      id = R.id.constraintLayout6;
      ConstraintLayout constraintLayout6 = ViewBindings.findChildViewById(rootView, id);
      if (constraintLayout6 == null) {
        break missingId;
      }

      id = R.id.guideline5;
      Guideline guideline5 = ViewBindings.findChildViewById(rootView, id);
      if (guideline5 == null) {
        break missingId;
      }

      ConstraintLayout layoutAlertDialog = (ConstraintLayout) rootView;

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.txtContentMessage;
      TextView txtContentMessage = ViewBindings.findChildViewById(rootView, id);
      if (txtContentMessage == null) {
        break missingId;
      }

      return new LayoutAlertDialogBinding((ConstraintLayout) rootView, btnNo, btnYes,
          constraintLayout6, guideline5, layoutAlertDialog, linearLayout, txtContentMessage);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
